name: WIP

on:
  push:
    branches: [ master ]


jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: |
        cd $(cat wip)
        make
